export default {
  loading: false,

  products: [
    {
      id: 1,
      name: 'fita-isolante',
      label: 'Fita Isolante',
      value: '6,90',
      img: 'img/fita-isolante.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Fita isolande de alta isolação e fixação para todos os ambientes',
      qtdForSale: 1,
    },
    {
      id: 2,
      name: 'cola-pvc-tigre',
      label: 'Cola PVC Tigre',
      value: '4,90',
      img: 'img/cola-pvc-tigre.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Cola para tubo PVC de fixação rápida e segura contra vazamento.',
      qtdForSale: 1,
    },
    {
      id: 3,
      name: 'conexao-t-tigre',
      label: 'Conexão "T" Tigre',
      value: '3,90',
      img: 'img/conexão-t-tigre.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Conexão em formato c/ rosca em "T" para toneiras',
      qtdForSale: 1,
    },
    {
      id: 4,
      name: 'pincel-tigre',
      label: 'Pincel Tigre',
      value: '5,90',
      img: 'img/picel-tigre.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Pincel de 2" resistente e durável',
      qtdForSale: 1,
    },
    {
      id: 5,
      name: 'saco-de-areia',
      label: 'Saco de Areia',
      value: '9,90',
      img: 'img/saco-de-areia.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Saco de areia lavada de 20Kg',
      qtdForSale: 1,
    },
    {
      id: 6,
      name: 'saco-de-pedra',
      label: 'Saco de Pedra',
      value: '8,90',
      img: 'img/saco-de-pedra.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Saco de pedra com 20kg tipo nº 2',
      qtdForSale: 1,
    },
    {
      id: 7,
      name: 'tinta-esmalte-preta-coral',
      label: 'Tinta Esmalte Coral Preto',
      value: '29,90',
      img: 'img/tinta-esmalte-preta-coral.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Tinta esmalte sintetico de cor preta',
      qtdForSale: 1,
    },
    {
      id: 8,
      name: 'alicate-universal-gedore',
      label: 'Alicate Universal Gedore',
      value: '59,90',
      img: 'img/alicate-universal-gedore.png',
      altImage: 'Descrição da imagem do produto',
      shortDescription: 'Alicate universal multiuso com isolação de 1000V',
      qtdForSale: 1,
    },
  ],

};
