export default {
  loading: false,
  cartProductList: [],

  // cartProductList: [
  //   {
  //     id: 1,
  //     name: 'fita-isolante',
  //     label: 'Fita Isolante',
  //     value: '6,90',
  //     img: 'img/fita-isolante.png',
  //     altImage: 'Descrição da imagem do produto',
  //     shortDescription: 'Fita isolande de alta isolação e fixação para todos os ambientes',
  //     qtdForSale: 1,
  //   },
  //   {
  //     id: 2,
  //     name: 'cola-pvc-tigre',
  //     label: 'Cola PVC Tigre',
  //     value: '4,90',
  //     img: 'img/cola-pvc-tigre.png',
  //     altImage: 'Descrição da imagem do produto',
  //     shortDescription: 'Cola para tubo PVC de fixação rápida e segura contra vazamento.',
  //     qtdForSale: 1,
  //   },
  //   {
  //     id: 3,
  //     name: 'conexao-t-tigre',
  //     label: 'Conexão "T" Tigre',
  //     value: '3,90',
  //     img: 'img/conexão-t-tigre.png',
  //     altImage: 'Descrição da imagem do produto',
  //     shortDescription: 'Conexão em formato c/ rosca em "T" para toneiras',
  //     qtdForSale: 1,
  //   },
  //   {
  //     id: 4,
  //     name: 'pincel-tigre',
  //     label: 'Pincel Tigre',
  //     value: '5,90',
  //     img: 'img/picel-tigre.png',
  //     altImage: 'Descrição da imagem do produto',
  //     shortDescription: 'Pincel de 2" resistente e durável',
  //     qtdForSale: 1,
  //   },
  // ],
};
